### ISSUE TITLE
Google API Key Usage

### ISSUE THREAD

**Issue by LeSnixzy** [meherpr/SwissRt#1]
Hello I've just got notified from google that you're using a google API Key from one of our projects. 

Could you please reach out to me so we can figure out what's that about.

Regards,
Marco
marco@tellssoehne.ch

**Comment by meherpr** [comment]
Hi Marco,

I am doing
  - an academic research
  - with no-commercial interest
on different COVID-19 policies by Swiss government.

I had uploaded the excel sheets we prepared about the policies, our python
code for analysis, along with the newspaper articles from swissinfo.ch,
thelocal.ch, etc which I collected as an evidence.

I apologize,
 - but I do not find tellssoehne.ch in the folder which I uploaded
 - do not know where the API id comes from, unless it got automatically
saved when I saved the html files from newspaper articles

Step forward,
  - the entire folder meherpr/SwissRt is open to public.
  - If you see where the sensitive files could be, I will be happy to find
a solution by removing that specific file.

Please let me know, and I will be happy to resolve the problem if you help
me identify it,

Many thanks and best wishes
meher

**Comment by LeSnixzy** [comment]
@meherpr No worries, could you please e-mail me. I feel like solving this bilateral rather than on here.

I'll close the issue.
